"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var GestorClub_1 = require("./GestorClub");
var club = new GestorClub_1.GestorClub('Inter Miami CF');
club.darAltaSocio();
club.darAltaSocio();
club.listarSocios();
club.buscarSocioxApellido('salias');
club.buscarSocioxApellido('hahaha');
club.buscarSocioxDni(31094435);
club.buscarSocioxDni(310945);
club.buscarSocioxDeporte('futbol');
