"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var cancion_1 = require("./cancion");
var cd_1 = require("./cd");
var cancion1 = new cancion_1.Cancion('Medias Negras', 'Sabina');
var cancion2 = new cancion_1.Cancion('No necesito nada', 'No te va a gustar');
var cancion3 = new cancion_1.Cancion('Vas a bailar', 'Ciro y los persas');
var cancion4 = new cancion_1.Cancion('Llenos de magia', 'La vela puerca');
var cancion5 = new cancion_1.Cancion('A la orilla de la chimenea', 'Sabina');
var cancion6 = new cancion_1.Cancion('Tratame suavemente', 'Sosa Stereo');
var cancion7 = new cancion_1.Cancion('Persiana americana', 'Sosa Stereo');
var CD = new cd_1.Cd;
CD.agregarCancion(cancion1);
CD.agregarCancion(cancion2);
CD.agregarCancion(cancion3);
CD.agregarCancion(cancion4);
CD.agregarCancion(cancion5);
CD.agregarCancion(cancion6);
CD.agregarCancion(cancion7);
console.log('');
CD.listarCD();
console.log('');
console.log("El cd tiene ".concat(CD.contarCanciones(), " canciones"));
console.log('');
CD.eliminarCancion(3);
console.log('');
var cancion8 = new cancion_1.Cancion('Verte reir', 'No te va a gustar');
CD.grabarCancion(4, cancion8);
console.log('');
CD.listarCD();
